//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineManagementAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrewMember
    {
        public int MemberId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> PositionId { get; set; }
        public string Phone { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<int> CrewId { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public Nullable<int> PassportCountryId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Crew Crew { get; set; }
        public virtual Office Office { get; set; }
        public virtual Position Position { get; set; }
    }
}
