//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineManagementAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respondent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Respondent()
        {
            this.Surveys = new HashSet<Survey>();
        }
    
        public string Departure { get; set; }
        public string Arrival { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string CabinType { get; set; }
        public int RespondentId { get; set; }
        public Nullable<int> ScheduleId { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Survey> Surveys { get; set; }
    }
}
