//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportManagerSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> AnswerId { get; set; }
        public Nullable<int> RespondentId { get; set; }
        public int SurveyId { get; set; }
        public Nullable<int> QuestionId { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual Question Question { get; set; }
        public virtual Respondent Respondent { get; set; }
    }
}
