//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportManagerSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginHistory
    {
        public int LoginId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> CrashId { get; set; }
        public System.DateTime LoginTime { get; set; }
        public Nullable<System.DateTime> LogoutTime { get; set; }
        public string Reason { get; set; }
    
        public virtual Crash Crash { get; set; }
        public virtual User User { get; set; }
    }
}
